### ISSUE TITLE
flask run fails with an Import error

### ISSUE THREAD

**Issue by kami619** [mr-teslaa/TaqwaSchool#27]
@mr-teslaa your application looks really cool, but I would like to try it out myself and hitting this error. Please let me know if I am doing something wrong here

here's the `.flaskenv` file

```
❯ cat .flaskenv
export FLASK_APP=run.py
export FLASK_ENV=development
export FLASK_DEBUG=1
```

running `flask run` fails with the below error

```
❯ flask run
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Serving Flask app 'run.py' (lazy loading)
 * Environment: development
 * Debug mode: on
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'run', an ImportError was raised.
~/code/learn_python/Junior_School_and_College master*                                                                                                                             00:39:08
Junior_School_and_College ❯
```

**Comment by NK-Inomine** [comment]
@mr-teslaa Hello am leraning flask with this project and am facing an issue that am struggling with, that is <<ImportError: cannot import name 'TimedJSONWebSignatureSerializer' from 'itsdangerous'>> I googled it, also checked on youtube but still couldn't solve it I will appreciate if you can explain me why am getting this error and how to fix. Thanks

**Comment by mr-teslaa** [comment]
@kami619, try to use your terminal instead 
```bash
$ export FLASK_APP=run.py
$ export FLASK_ENV=development
or 
$ export FLASK_DEBUG=1
$ flask run
```

**Comment by kami619** [comment]
@mr-teslaa 

still happens while using the terminal, as you suggested.

```
> export FLASK_APP=run.py
> export FLASK_ENV=development
> flask run
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Serving Flask app 'run.py' (lazy loading)
 * Environment: development
 * Debug mode: on
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'run', an ImportError was raised.
```

**Comment by mr-teslaa** [comment]
@kami619 

Could you please give me more information about your error, that would be great

**Comment by NK-Inomine** [comment]
I fixed thanks anyway. By the way If I need a full complete project about
management systems using advanced flask features what is the process to
work with you ?

**Comment by mr-teslaa** [comment]
@NK-Inomine 
If you want to add new feature, describe your idea what you are thinking to add. Then you could create pull request.
That's it
